@startuml
!include .\\DataStructureLibrary\Edge.puml
!include .\\DataStructureLibrary\Graph.puml
!include .\\DataStructureLibrary\SinglyLinkedList.puml
!include .\\DataStructureLibrary\Vertex.puml
!include .\\MetroNetApp\Program.puml
!include .\\MetroNetApp\classes\CityNetwork.puml
!include .\\MetroNetApp\classes\TrenchRoute.puml
!include .\\DataStructureLibrary\obj\Debug\net10.0\.NETCoreApp,Version=v10.0.AssemblyAttributes.puml
!include .\\DataStructureLibrary\obj\Debug\net10.0\DataStructureLibrary.AssemblyInfo.puml
!include .\\DataStructureLibrary\obj\Debug\net10.0\DataStructureLibrary.GlobalUsings.g.puml
!include .\\MetroNetApp\obj\Debug\net10.0\.NETCoreApp,Version=v10.0.AssemblyAttributes.puml
!include .\\MetroNetApp\obj\Debug\net10.0\MetroNetApp.AssemblyInfo.puml
!include .\\MetroNetApp\obj\Debug\net10.0\MetroNetApp.GlobalUsings.g.puml
@enduml
